### ISSUE TITLE
Texture Wither Heart potential copyright infringement

### ISSUE THREAD

**Issue by Razsiel** [Quarris/Enchantability#10]
This is not an attack, just to inform :)

The title is descriptive enough. The Wither Heart icon is a potential infringement on the Terraria texture for the [Demon Heart](https://terraria.gamepedia.com/Demon_Heart). While in theory it is unlikely that Re-Logic will file a copyright ingringment and that this could be a temporary texture, be aware that this is technically not allowed.

**Comment by Quarris** [comment]
Yes, I am aware. Thank you for notifying me.
