### ISSUE TITLE
[suggestion] Make it so multiple of the same enchants stack

### ISSUE THREAD

**Issue by PokeMaserJ** [Quarris/Enchantability#11]
As an example flame stacking would increase the speed in which TEs tick, so 2 flame enchants would be faster than just 1. And so on and so on. Now, that might be a tad bit overpowered and I would understand if you don't add it.

**Comment by Quarris** [comment]
The system is not designed to accept multiple enchants of the same type and adding an exception just for that would add inconsistency.
