### ISSUE TITLE
Stuck in air with frozen walker entchantment

### ISSUE THREAD

**Issue by slasherbane** [Quarris/Enchantability#2]
hi man, please tell me why i suppose to do to go back on th floor please . because at the moment i m stuck a 90 y block in my save :/

**Comment by Quarris** [comment]
Did you find a way down orr....?

**Comment by slasherbane** [comment]
I found by jump running....thk

**Comment by Quarris** [comment]
Yeah thats the way. If you can think of a different way to make them disappear, let me know \o/
