### ISSUE TITLE
Enchantability Error

### ISSUE THREAD

**Issue by Purexbeatdown** [Quarris/Enchantability#3]
"Enchantability (enchantability) encountered an error during the common_setup event phase".
[ErrorLog.txt](https://github.com/Quarris/Enchantability/files/4281119/ErrorLog.txt)

**Comment by Quarris** [comment]
Has this happened on a specific modpack? Or a collection of mods? If so, can you let me know what pack or which mods were used?

**Comment by Purexbeatdown** [comment]
My own collection of mods, quite a few of them.

**Comment by Purexbeatdown** [comment]
I can list them all if you want?

**Comment by Quarris** [comment]
Not yet, I'll have a look coz I think I know what the problem is

**Comment by Purexbeatdown** [comment]
Ok, just let me know if you want me to list them.

**Comment by Quarris** [comment]
Ill release in a sec. Let me know if it works when its out. Reopen this issue if you have more problems like this

**Comment by Quarris** [comment]
It should be released now

**Comment by Purexbeatdown** [comment]
Yup, whatever you fixed worked. Thank you.

**Comment by Quarris** [comment]
\o/
