### ISSUE TITLE
Config file/Descriptions

### ISSUE THREAD

**Issue by Purexbeatdown** [Quarris/Enchantability#4]
I can't seem to find the config file or the descriptions for what the enchants do when on you. Some enchantment descriptions are broken in game when you press Left-Shift.

**Comment by Quarris** [comment]
Umm which ones? I wouldnt put it past me that i forgot to add the localization for them. Its 2am rn so im heading to sleep but ill fix them in the morning

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Purexbeatdown** [comment]
The Enchants that have broken descriptions are Power 1-5 for the Bow and Flame for the Bow.
And I still haven't been able to find the config file.

**Comment by Quarris** [comment]
Yeah the descriptions are not part of a config. If you want to change them yourself you would need a resource pack

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Purexbeatdown** [comment]
Oh, I thought there might have been a text document or something that had them.
