### ISSUE TITLE
Config File Path

### ISSUE THREAD

**Issue by Purexbeatdown** [Quarris/Enchantability#5]
Still unable to find the path to the Config folder. Have checked every folder in my minecraft install.

**Comment by Quarris** [comment]
What? The config file will be in the modded install folder

**Comment by Purexbeatdown** [comment]
Yeah, but it's not... I have all my other mod in there but Enchantability isn't there. Only thing I can find having to do with Enchantability is the jar file.

**Comment by Purexbeatdown** [comment]
There's no .toml file or .txt file having to do with Enchantability anywhere.

**Comment by Purexbeatdown** [comment]
Sorry didn't see you put a new update out before I commented. Config File is there now with newest update.

**Comment by Quarris** [comment]
Yeah I was gonna say :P

**Comment by Purexbeatdown** [comment]
Thank you for all the fixes the past couple days :)

**Comment by Quarris** [comment]
All good, keep them coming! (but not too fast, I have studies to study for)
