### ISSUE TITLE
Enchantability-1.16.1-8.1-sources.jar has mods that were not found

### ISSUE THREAD

**Issue by Mystic-Taco** [Quarris/Enchantability#7]
[latest.log](https://github.com/Quarris/Enchantability/files/4855967/latest.log)

I run into this error when Minecraft is finished loading, can't figure out what I can do differently, tried reinstalling

**Comment by Quarris** [comment]
Thats weird. Ive done this port quickly at 3am so I expected some bugs and thats why its an alpha version :P . Thanks for letting me know, I'll check it out when I have some time today

**Comment by Quarris** [comment]
Honestly I'm not sure what the problem is. I will wait for future updates where forge is a bit more updated
